# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentlayer" do
  version "1.9.3"

  on_macos do
    on_arm do
      sha256 "67fcdf4448089d3f5bb3f0322a32695ccab99c1673247423f3b968088cebd461"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d1a41cad05c2f2ab0549748e5234258806f5884c77403a6427260526a8d1a28"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "440a5d22c6cc1135c3e9d0e2abc921301afa30819490c48d54adeb5d7cb9a637"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7c96d1a931450de8eed43eee085271c151987528ca3f97fd9e3a4a9a9f579877"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentlayer"
  desc "iTerm2+tmux 멀티 에이전트 관제탑 — 상태·알림·worktree"
  homepage "https://github.com/netwaif/agentlayer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentlayer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentlayer"]
    end
  end

  # No zap stanza required
end
