# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentlayer" do
  version "1.6.3"

  on_macos do
    on_arm do
      sha256 "216c665ff94941a1f00e4c502544ff086fefe9307111e3accd62f2c36c86de82"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9158a379fe318d4b9406d7450df436f6adf8d20310217aaa948dba648c3c24ec"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8499405c635389ca6e76ce520e0e54a35ff9fdd338cbb126fcdc0731e35f9405"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b8cd0c6453ab4638a5497edb4ee060ba98ee2579034e3cd5c4cbe86d8705a09"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentlayer"
  desc "iTerm2+tmux 멀티 에이전트 관제탑 — 상태·알림·worktree"
  homepage "https://github.com/netwaif/agentlayer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentlayer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentlayer"]
    end
  end

  # No zap stanza required
end
