# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentlayer" do
  version "1.17.2"

  on_macos do
    on_arm do
      sha256 "cbbeff8bd2b6f9e481dbfb8c139f7aa0f3479a3b7eaad4c4665cbf0b1c64f62e"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "76b495fd0e59b57d4918dbf177fd9934dd0fe9b2949f086bb3cf9f16e8a7fd1a"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b52577eea590d14d3588291e7118487bb642e7b31d4f45a9948ca182d38ce2aa"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0e152c931be96460c9d1d1990faf52a934f6a3b402c8343585f185b71c0de5f9"
      url "https://github.com/netwaif/agentlayer/releases/download/v#{version}/agentlayer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agentlayer"
  desc "iTerm2+tmux 멀티 에이전트 관제탑 — 상태·알림·worktree"
  homepage "https://github.com/netwaif/agentlayer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentlayer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agentlayer"]
    end
  end

  # No zap stanza required
end
