# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentlayer < Formula
  desc "iTerm2+tmux 멀티 에이전트 관제탑 — 상태·알림·worktree"
  homepage "https://github.com/netwaif/agentlayer"
  version "1.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/netwaif/agentlayer/releases/download/v1.1.0/agentlayer_1.1.0_darwin_amd64.tar.gz"
    sha256 "9df45adc339a57d31c10f55db7aad2829c4adca9de3c06f2f0f0a805abf397a2"

    define_method(:install) do
      bin.install "agentlayer"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/netwaif/agentlayer/releases/download/v1.1.0/agentlayer_1.1.0_darwin_arm64.tar.gz"
    sha256 "1c2d64fb6889aa2e54640b5f46bd1bc08dc8ea1283130428afddc909bd3fc3ed"

    define_method(:install) do
      bin.install "agentlayer"
    end
  end

  test do
    system "#{bin}/agentlayer", "version"
    system "#{bin}/agentlayer", "status", "--json"
  end
end
